import React, { PureComponent } from 'react'

export default class TestSlideComponent extends PureComponent {
  render() {
    return (
      <React.Fragment>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequuntur eius eligendi porro voluptatem deleniti voluptas ipsam, nostrum aut ad consequatur consectetur assumenda pariatur, delectus, omnis magnam illo nam blanditiis.</p>
      </React.Fragment>
    )
  }
}
